services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=sqlserver
      - DB_USER=sa
      - DB_PASSWORD=SuperStrongPassword123!
      - DB_NAME=core360
      - DB_PORT=1433
    depends_on:
      - sqlserver
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M

volumes:
  sqlserver_data:
