-- =================================================================
-- CORE 360 - INITIAL SCHEMA FOR SQL SERVER
-- Generated automatically from Knex Migrations
-- =================================================================

CREATE TABLE [zonas] ([id] int identity(1,1) not null primary key, [nombre] nvarchar(100) not null, [created_at] datetime2 not null CONSTRAINT [zonas_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [zonas_updated_at_default] DEFAULT CURRENT_TIMESTAMP);

CREATE UNIQUE INDEX [zonas_nombre_unique] ON [zonas] ([nombre]) WHERE [nombre] IS NOT NULL;

CREATE TABLE [usuarios] ([id] int identity(1,1) not null primary key, [nombre] nvarchar(255) not null, [correo] nvarchar(255) not null, [contrasena] nvarchar(255) not null, [permisos] nvarchar(255) not null, [cargos] nvarchar(255) null, [jefatura_id] int null, [gerencia_id] int null, [zona_id] int null, [vistas_permitidas] nvarchar(max) null, [requiere_cambio_clave] bit CONSTRAINT [usuarios_requiere_cambio_clave_default] DEFAULT '0', [permite_traspaso] bit CONSTRAINT [usuarios_permite_traspaso_default] DEFAULT '0', [sync_delta_token] nvarchar(max) null, [ultima_sincronizacion] datetime2 null, [preferencias] nvarchar(max) null, [created_at] datetime2 not null CONSTRAINT [usuarios_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [usuarios_updated_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [usuarios_zona_id_foreign] FOREIGN KEY ([zona_id]) REFERENCES [zonas] ([id]));

CREATE UNIQUE INDEX [usuarios_correo_unique] ON [usuarios] ([correo]) WHERE [correo] IS NOT NULL;

ALTER TABLE [usuarios] ADD CONSTRAINT [usuarios_jefatura_id_foreign] FOREIGN KEY ([jefatura_id]) REFERENCES [usuarios] ([id]) ON DELETE NO ACTION;

ALTER TABLE [usuarios] ADD CONSTRAINT [usuarios_gerencia_id_foreign] FOREIGN KEY ([gerencia_id]) REFERENCES [usuarios] ([id]) ON DELETE NO ACTION;

CREATE TABLE [empresas] ([id] int identity(1,1) not null primary key, [nombre] nvarchar(255) not null, [jefatura_id] int null, [zona_id] int CONSTRAINT [empresas_zona_id_default] DEFAULT '1', [rut] nvarchar(255) null, [razon_social] nvarchar(300) null, [estado_seguimiento] nvarchar(255) CONSTRAINT [empresas_estado_seguimiento_default] DEFAULT 'pendiente', [fecha_concretada] date null, [fecha_solicitada] date null, [created_at] datetime2 not null CONSTRAINT [empresas_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [empresas_updated_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [empresas_jefatura_id_foreign] FOREIGN KEY ([jefatura_id]) REFERENCES [usuarios] ([id]) ON DELETE SET NULL, CONSTRAINT [empresas_zona_id_foreign] FOREIGN KEY ([zona_id]) REFERENCES [zonas] ([id]));

CREATE TABLE [usuario_gerencias] ([usuario_id] int not null, [gerencia_id] int not null, CONSTRAINT [usuario_gerencias_usuario_id_foreign] FOREIGN KEY ([usuario_id]) REFERENCES [usuarios] ([id]) ON DELETE CASCADE, CONSTRAINT [usuario_gerencias_gerencia_id_foreign] FOREIGN KEY ([gerencia_id]) REFERENCES [usuarios] ([id]) ON DELETE NO ACTION, CONSTRAINT [usuario_gerencias_pkey] PRIMARY KEY ([usuario_id], [gerencia_id]));

CREATE TABLE [encuesta_dimensiones] ([id] int identity(1,1) not null primary key, [nombre] nvarchar(100) not null, [descripcion] nvarchar(max) null, [created_at] datetime2 not null CONSTRAINT [encuesta_dimensiones_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [encuesta_dimensiones_updated_at_default] DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE [encuesta_templates] ([id] int identity(1,1) not null primary key, [nombre] nvarchar(255) not null, [descripcion] nvarchar(max) null, [version] int CONSTRAINT [encuesta_templates_version_default] DEFAULT '1', [activo] int CONSTRAINT [encuesta_templates_activo_default] DEFAULT '1', [created_at] datetime2 not null CONSTRAINT [encuesta_templates_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [encuesta_templates_updated_at_default] DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE [encuesta_catalogo_preguntas] ([id] int identity(1,1) not null primary key, [dimension_id] int null, [subdimension] nvarchar(255) null, [texto] nvarchar(max) not null, [tipo] nvarchar(255) not null, [escala] int CONSTRAINT [encuesta_catalogo_preguntas_escala_default] DEFAULT '5', [es_nps] bit CONSTRAINT [encuesta_catalogo_preguntas_es_nps_default] DEFAULT '0', [opciones_json] nvarchar(max) null, [activo] int CONSTRAINT [encuesta_catalogo_preguntas_activo_default] DEFAULT '1', CONSTRAINT [encuesta_catalogo_preguntas_dimension_id_foreign] FOREIGN KEY ([dimension_id]) REFERENCES [encuesta_dimensiones] ([id]) ON DELETE SET NULL);

CREATE TABLE [encuesta_template_preguntas] ([template_id] int not null, [pregunta_id] int not null, [orden] int CONSTRAINT [encuesta_template_preguntas_orden_default] DEFAULT '0', [requerida] bit CONSTRAINT [encuesta_template_preguntas_requerida_default] DEFAULT '1', CONSTRAINT [encuesta_template_preguntas_template_id_foreign] FOREIGN KEY ([template_id]) REFERENCES [encuesta_templates] ([id]) ON DELETE CASCADE, CONSTRAINT [encuesta_template_preguntas_pregunta_id_foreign] FOREIGN KEY ([pregunta_id]) REFERENCES [encuesta_catalogo_preguntas] ([id]) ON DELETE CASCADE, CONSTRAINT [encuesta_template_preguntas_pkey] PRIMARY KEY ([template_id], [pregunta_id]));

CREATE TABLE [encuestas] ([id] int identity(1,1) not null primary key, [template_id] int not null, [empresa_id] int null, [ejecutiva_id] int null, [token] nvarchar(100) not null, [estado] nvarchar(255) CONSTRAINT [encuestas_estado_default] DEFAULT 'pendiente', [reunion_id] int null, [enviado_a] nvarchar(max) null, [activo] bit CONSTRAINT [encuestas_activo_default] DEFAULT '1', [fecha_creacion] datetime2 CONSTRAINT [encuestas_fecha_creacion_default] DEFAULT CURRENT_TIMESTAMP, [fecha_respuesta] datetime2 null, CONSTRAINT [encuestas_template_id_foreign] FOREIGN KEY ([template_id]) REFERENCES [encuesta_templates] ([id]), CONSTRAINT [encuestas_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]), CONSTRAINT [encuestas_ejecutiva_id_foreign] FOREIGN KEY ([ejecutiva_id]) REFERENCES [usuarios] ([id]));

CREATE UNIQUE INDEX [encuestas_token_unique] ON [encuestas] ([token]) WHERE [token] IS NOT NULL;

CREATE TABLE [encuesta_respuestas] ([id] int identity(1,1) not null primary key, [encuesta_id] int not null, [pregunta_id] int not null, [valor_texto] nvarchar(max) null, [valor_numerico] decimal(10, 2) null, [created_at] datetime2 CONSTRAINT [encuesta_respuestas_created_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [encuesta_respuestas_encuesta_id_foreign] FOREIGN KEY ([encuesta_id]) REFERENCES [encuestas] ([id]) ON DELETE CASCADE, CONSTRAINT [encuesta_respuestas_pregunta_id_foreign] FOREIGN KEY ([pregunta_id]) REFERENCES [encuesta_catalogo_preguntas] ([id]));

CREATE TABLE [empresa_seguimiento_log] ([id] int identity(1,1) not null primary key, [empresa_id] int not null, [estado] nvarchar(100) not null, [fecha] date null, [usuario_id] int null, [reunion_id] nvarchar(500) null, [asunto] nvarchar(255) null, [created_at] datetime2 CONSTRAINT [empresa_seguimiento_log_created_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [empresa_seguimiento_log_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]) ON DELETE CASCADE, CONSTRAINT [empresa_seguimiento_log_usuario_id_foreign] FOREIGN KEY ([usuario_id]) REFERENCES [usuarios] ([id]));

CREATE TABLE [empresa_dominios] ([id] int identity(1,1) not null primary key, [empresa_id] int not null, [dominio] nvarchar(100) not null, [created_at] datetime2 CONSTRAINT [empresa_dominios_created_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [empresa_dominios_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]) ON DELETE CASCADE);

CREATE UNIQUE INDEX [empresa_dominios_empresa_id_dominio_unique] ON [empresa_dominios] ([empresa_id], [dominio]) WHERE [empresa_id] IS NOT NULL AND [dominio] IS NOT NULL;

CREATE TABLE [empresa_contactos] ([id] int identity(1,1) not null primary key, [empresa_id] int not null, [correo] nvarchar(255) not null, [nombre] nvarchar(255) null, [created_at] datetime2 CONSTRAINT [empresa_contactos_created_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [empresa_contactos_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]) ON DELETE CASCADE);

CREATE UNIQUE INDEX [empresa_contactos_empresa_id_correo_unique] ON [empresa_contactos] ([empresa_id], [correo]) WHERE [empresa_id] IS NOT NULL AND [correo] IS NOT NULL;

CREATE TABLE [teams_eventos] ([id] int identity(1,1) not null primary key, [event_id] nvarchar(500) not null, [ical_uid] nvarchar(500) null, [usuario_id] int not null, [empresa_id] int null, [asunto] nvarchar(500) not null, [fecha] date null, [hora] time null, [hora_fin] time null, [estado] nvarchar(255) CONSTRAINT [teams_eventos_estado_default] DEFAULT 'agendada', [es_online] bit CONSTRAINT [teams_eventos_es_online_default] DEFAULT '1', [asistentes] nvarchar(max) null, [join_url] nvarchar(max) null, [ultima_sync] datetime2 null, [organizador] nvarchar(max) null, [body_preview] nvarchar(max) null, [created_at] datetime2 not null CONSTRAINT [teams_eventos_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [teams_eventos_updated_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [teams_eventos_usuario_id_foreign] FOREIGN KEY ([usuario_id]) REFERENCES [usuarios] ([id]) ON DELETE CASCADE, CONSTRAINT [teams_eventos_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]) ON DELETE SET NULL);

CREATE UNIQUE INDEX [teams_eventos_event_id_unique] ON [teams_eventos] ([event_id]) WHERE [event_id] IS NOT NULL;

CREATE TABLE [minutas] ([id] int identity(1,1) not null primary key, [id_minuta] nvarchar(30) not null, [teams_evento_id] int null, [ejecutiva_id] int not null, [empresa_id] int null, [tipo_reu] nvarchar(100) null, [enviado_a] nvarchar(max) null, [enviado_por] nvarchar(255) null, [participantes] nvarchar(max) null, [motivo_reu] nvarchar(max) null, [minuta] nvarchar(max) null, [form_f] nvarchar(max) null, [fecha_reu] date null, [hora] nvarchar(10) null, [lugar] nvarchar(255) CONSTRAINT [minutas_lugar_default] DEFAULT 'Teams', [documentos_adjuntos] nvarchar(max) null, [estado_envio] nvarchar(255) CONSTRAINT [minutas_estado_envio_default] DEFAULT 'borrador', [archivos_nombres] nvarchar(max) null, [programar_encuesta] bit CONSTRAINT [minutas_programar_encuesta_default] DEFAULT '0', [encuesta_tipo] nvarchar(100) null, [encuesta_programada_para] datetime2 null, [encuesta_estado_envio] nvarchar(20) CONSTRAINT [minutas_encuesta_estado_envio_default] DEFAULT 'pendiente', [encuesta_relacionada] bit CONSTRAINT [minutas_encuesta_relacionada_default] DEFAULT '0', [encuesta_destinatario] nvarchar(255) null, [texto_previo] nvarchar(max) null, [link_video] nvarchar(max) null, [es_retroactiva] bit CONSTRAINT [minutas_es_retroactiva_default] DEFAULT '0', [created_at] datetime2 not null CONSTRAINT [minutas_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [minutas_updated_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [minutas_teams_evento_id_foreign] FOREIGN KEY ([teams_evento_id]) REFERENCES [teams_eventos] ([id]) ON DELETE SET NULL, CONSTRAINT [minutas_ejecutiva_id_foreign] FOREIGN KEY ([ejecutiva_id]) REFERENCES [usuarios] ([id]), CONSTRAINT [minutas_empresa_id_foreign] FOREIGN KEY ([empresa_id]) REFERENCES [empresas] ([id]));

CREATE UNIQUE INDEX [minutas_id_minuta_unique] ON [minutas] ([id_minuta]) WHERE [id_minuta] IS NOT NULL;

CREATE TABLE [sync_log] ([id] int identity(1,1) not null primary key, [tipo] nvarchar(50) not null CONSTRAINT [sync_log_tipo_default] DEFAULT 'diaria', [ejecutado_at] datetime2 not null CONSTRAINT [sync_log_ejecutado_at_default] DEFAULT CURRENT_TIMESTAMP, [resultado] nvarchar(max) null);

CREATE TABLE [nuevos_negocios] ([id] int identity(1,1) not null primary key, [holding] nvarchar(200) null, [estado_contacto] nvarchar(50) not null CONSTRAINT [nuevos_negocios_estado_contacto_default] DEFAULT 'PROSPECTO', [rut] nvarchar(20) null, [razon_social] nvarchar(300) null, [evento] nvarchar(200) null, [indicador] nvarchar(100) null, [asistio_evento] nvarchar(10) CONSTRAINT [nuevos_negocios_asistio_evento_default] DEFAULT 'No', [zona] nvarchar(50) null, [monto_1_porciento] decimal(15, 2) CONSTRAINT [nuevos_negocios_monto_1_porciento_default] DEFAULT '0', [tasa_administracion] decimal(5, 4) CONSTRAINT [nuevos_negocios_tasa_administracion_default] DEFAULT '0', [monto_administracion] decimal(15, 2) CONSTRAINT [nuevos_negocios_monto_administracion_default] DEFAULT '0', [otic_actual] nvarchar(100) null, [mes_envio_propuesta] nvarchar(50) null, [jefa_cartera] nvarchar(150) null, [estado] nvarchar(100) CONSTRAINT [nuevos_negocios_estado_default] DEFAULT 'Prospecto', [aporte_ingresado] decimal(15, 2) CONSTRAINT [nuevos_negocios_aporte_ingresado_default] DEFAULT '0', [fecha_autoriza_propuesta] nvarchar(100) null, [contacto] nvarchar(200) null, [contacto_2] nvarchar(200) null, [correo] nvarchar(300) null, [cargo] nvarchar(200) null, [celular_telefono] nvarchar(100) null, [comentarios] nvarchar(max) null, [fecha_reunion] date null, [created_at] datetime2 not null CONSTRAINT [nuevos_negocios_created_at_default] DEFAULT CURRENT_TIMESTAMP, [updated_at] datetime2 not null CONSTRAINT [nuevos_negocios_updated_at_default] DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE [nuevos_negocios_historial] ([id] int identity(1,1) not null primary key, [negocio_id] int not null, [campo_modificado] nvarchar(50) not null, [valor_anterior] nvarchar(200) null, [valor_nuevo] nvarchar(200) null, [usuario] nvarchar(150) null, [created_at] datetime2 CONSTRAINT [nuevos_negocios_historial_created_at_default] DEFAULT CURRENT_TIMESTAMP, CONSTRAINT [nuevos_negocios_historial_negocio_id_foreign] FOREIGN KEY ([negocio_id]) REFERENCES [nuevos_negocios] ([id]) ON DELETE CASCADE);

CREATE TABLE [audit_log] ([id] int identity(1,1) not null primary key, [accion] nvarchar(100) not null, [entidad] nvarchar(50) not null, [entidad_id] nvarchar(100) null, [usuario_id] int null, [usuario_nombre] nvarchar(255) null, [ejecutiva_id] int null, [ejecutiva_nombre] nvarchar(255) null, [empresa_id] int null, [empresa_nombre] nvarchar(255) null, [detalles] nvarchar(max) null, [ip_address] nvarchar(45) null, [created_at] datetime2 CONSTRAINT [audit_log_created_at_default] DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX [audit_log_accion_index] ON [audit_log] ([accion]);

CREATE INDEX [audit_log_usuario_id_index] ON [audit_log] ([usuario_id]);

CREATE INDEX [audit_log_entidad_entidad_id_index] ON [audit_log] ([entidad], [entidad_id]);

CREATE INDEX [audit_log_created_at_index] ON [audit_log] ([created_at]);